#!/usr/bin/env python3
"""Generate a formatted Markdown annotation file for any document type."""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def generate_markdown(
    input_path: str,
    notes: str,
    doc_type: str,
    title: str = "",
    metadata: dict | None = None,
) -> str:
    """Generate a complete Markdown annotation document."""
    p = Path(input_path)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    type_labels = {
        "presentation": "Presentation Speaker Notes",
        "paper": "Paper Reading Notes",
        "document": "Document Summary",
        "spreadsheet": "Data Analysis Report",
        "audio": "Audio Transcription Notes",
        "web": "Web Content Summary",
        "notebook": "Notebook Review",
        "text": "Key Insights",
    }

    label = type_labels.get(doc_type, "Annotation Notes")

    lines = [
        f"# {title or p.stem} — {label}",
        "",
        f"- **Source**: `{input_path}`",
        f"- **Generated**: {now}",
        f"- **Type**: {doc_type}",
    ]

    if metadata:
        for k, v in metadata.items():
            lines.append(f"- **{k}**: {v}")

    lines.extend([
        "",
        "---",
        "",
        "## Annotations",
        "",
        notes,
        "",
        "---",
        "",
        f"*Generated by [doc-annotator](https://github.com/fyz2025/doc-annotator)*",
    ])

    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a formatted Markdown annotation file."
    )
    parser.add_argument("--input", required=True, type=Path, help="Original source file path")
    parser.add_argument("--output", required=True, type=Path, help="Output .md file path")
    parser.add_argument("--notes", required=True, type=Path, help="Notes content (text or JSON)")
    parser.add_argument("--type", default="text", help="Document type category")
    parser.add_argument("--title", default="", help="Document title")
    parser.add_argument("--meta", type=Path, help="Optional JSON metadata file")
    args = parser.parse_args(argv)

    notes_text = args.notes.read_text(encoding="utf-8")
    if args.notes.suffix == ".json":
        data = json.loads(notes_text)
        notes_text = data.get("notes", data.get("content", str(data)))

    metadata = None
    if args.meta and args.meta.exists():
        metadata = json.loads(args.meta.read_text(encoding="utf-8"))

    content = generate_markdown(
        str(args.input), notes_text, args.type,
        title=args.title, metadata=metadata,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"saved: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
